repos:
  - repo: local
    hooks:
      - id: sync-pixi-pyproject
        name: Sync pixi.toml and pyproject.toml
        entry: pixi run sync
        language: system
        stages: [pre-commit]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 'v2.29.4'
    hooks:
      - id: pyproject-fmt
