[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "bible"
version = "0.8.0"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dependencies = [
  "beautifulsoup4>=4.15,<5",
  "clypi>=1.9.1,<2",
  "loguru>=0.7.3,<0.8",
  "niquests>=3.21.1,<4",
  "pydantic-settings>=2.15,<3",
  "rich>=15,<16",
  "textual>=8.2.8",
]
scripts.bible-cli = "bible.cli.cli:main"
scripts.bible-tui = "bible.tui.tui:main"
